### PR TITLE
Add GitHub Actions to publish to GitHub Pages

### PR DESCRIPTION
**Pull request by hokorobi**
Push to master branch to publish to GitHub Pages.
Like this. https://hokorobi.github.io/plantuml-syntax-test/

### CODE REVIEW

**Comment by aklt** [comment]
Nice!  I will take a look at this soon :-)

**Comment by aklt** [comment]
@hokorobi I noticed that the Latex is not being rendered, here: https://hokorobi.github.io/plantuml-syntax-test/#uml/reference_19-01-1_Standalone-diagram

Is it possible to get this working?

**Comment by hokorobi** [comment]
Oh sure, I don't usually use LaTeX, so I am not able to render it in my environment either.
I think it will take some time to respond.

**Comment by aklt** [comment]
I got it to work locally, but I am not sure how it goes with github actions.
Anyway this repo is just to find errors in the plantuml syntax plugin so I think we probably don't need the latex rendered.  what do you think?

**Comment by hokorobi** [comment]
> Anyway this repo is just to find errors in the plantuml syntax plugin so I think we probably don't need the latex rendered. what do you think?

Agreed. 👍

**Comment by aklt** [comment]
Great! :-)

**Comment by hokorobi** [comment]
Thank you!
But https://aklt.github.io/plantuml-syntax-test/ is not equivalent to https://hokorobi.github.io/plantuml-syntax-test/.
Why is that?
Are you set up to upload README.md to GitHub pages?

**Pull request merged**
