### PR TITLE
Follow reference 1.2021.2

### PR DESCRIPTION
**Pull request by hokorobi**
https://plantuml.com/en/guide

### CODE REVIEW

**Comment by aklt** [comment]
Just saw this now, great work!

Looking forward to this :-)

**Comment by hokorobi** [comment]
Thanks!
I'll be making progress little by little.

**Comment by aklt** [comment]
Is it allright if I merge this? :-)

**Comment by hokorobi** [comment]
I plan to write up to chapter 27, so please wait a while longer.

**Comment by aklt** [comment]
No worries, I will wait :)

**Comment by hokorobi** [comment]
@aklt I'd appreciate it if you could check it out and merge it if it looks good.

**Comment by aklt** [comment]
@hokorobi Thank you! I will have a look this evening

**Comment by aklt** [comment]
@hokorobi  Thank you very much, that was a big upgrade.

**Comment by hokorobi** [comment]
Thank you!

**Pull request merged**
