### PR TITLE
Add  PlantUML Language Reference samples

### PR DESCRIPTION
**Pull request by hokorobi**
I am still working so I will not merge.

I added samples for the time being.
I think that there are wrong because I worked manually.

Are there ideas about file names?

### CODE REVIEW

**Comment by aklt** [comment]
Wow, this is really great!   So many samples!

About file names I am not sure.  I like your scheme of referencing sections
in the manual.  (I assume the file names are manual references :))

**Comment by aklt** [comment]
Alternatively we could name files according to their content?  I don't
think it is so important as long as the names are unique and we can reference
them.  What do you think?

Thanks for the large amount of work!

**Comment by hokorobi** [comment]
Thank you for your comment.
I thought that it might be better to include the contents in the file name,
but for the moment I think I will leave it as it is.

**Comment by hokorobi** [comment]
It seems there will be no problem so merge.

**Pull request merged**
